import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastProvider } from "@/components/providers/toaster-provider";
import { ConfettiProvider } from "@/components/providers/confetti-provider";
import RegisterModal from "@/components/modals/RegisterModal";
import EventModal from "@/components/modals/EventModal";
import UpdateModal from "@/components/modals/UpdateModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="">
            <ConfettiProvider />
            <ToastProvider />
            <RegisterModal />
            <EventModal />
            <UpdateModal />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
